// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export enum AIMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AIModeHat = "hat",
    AIModeHatPro = "hat-pro",
};

export class ChatStreamRequest {
    "streamId": number;
    "messages": ConversationTurn[];
    "systemPrompt": string;
    "mode": AIMode;
    "temperature": number;
    "maxTokens": number;
    "images"?: string[];
    "roomId"?: string | null;
    "roomShare": boolean;
    "sourceMessageId"?: string | null;
    "idToken"?: string;
    "idempotencyKey"?: string;

    /** Creates a new ChatStreamRequest instance. */
    constructor($$source: Partial<ChatStreamRequest> = {}) {
        if (!("streamId" in $$source)) {
            this["streamId"] = 0;
        }
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }
        if (!("systemPrompt" in $$source)) {
            this["systemPrompt"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = AIMode.$zero;
        }
        if (!("temperature" in $$source)) {
            this["temperature"] = 0;
        }
        if (!("maxTokens" in $$source)) {
            this["maxTokens"] = 0;
        }
        if (!("roomShare" in $$source)) {
            this["roomShare"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatStreamRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatStreamRequest {
        const $$createField1_0 = $$createType1;
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField1_0($$parsedSource["messages"]);
        }
        if ("images" in $$parsedSource) {
            $$parsedSource["images"] = $$createField6_0($$parsedSource["images"]);
        }
        return new ChatStreamRequest($$parsedSource as Partial<ChatStreamRequest>);
    }
}

export class ClipboardImage {
    "mimeType": string;
    "dataUrl": string;
    "width": number;
    "height": number;

    /** Creates a new ClipboardImage instance. */
    constructor($$source: Partial<ClipboardImage> = {}) {
        if (!("mimeType" in $$source)) {
            this["mimeType"] = "";
        }
        if (!("dataUrl" in $$source)) {
            this["dataUrl"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClipboardImage instance from a string or object.
     */
    static createFrom($$source: any = {}): ClipboardImage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClipboardImage($$parsedSource as Partial<ClipboardImage>);
    }
}

export class ClipboardPayload {
    "text": string;
    "image"?: ClipboardImage | null;

    /** Creates a new ClipboardPayload instance. */
    constructor($$source: Partial<ClipboardPayload> = {}) {
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClipboardPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): ClipboardPayload {
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("image" in $$parsedSource) {
            $$parsedSource["image"] = $$createField1_0($$parsedSource["image"]);
        }
        return new ClipboardPayload($$parsedSource as Partial<ClipboardPayload>);
    }
}

export class ClipboardSettings {
    "enabled": boolean;
    "copyResponseToClipboard": boolean;
    "maxResponseLength": number;
    "appendMode": boolean;
    "soundOnComplete": boolean;
    "captureImages": boolean;
    "flash": FlashSettings;

    /** Creates a new ClipboardSettings instance. */
    constructor($$source: Partial<ClipboardSettings> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("copyResponseToClipboard" in $$source)) {
            this["copyResponseToClipboard"] = false;
        }
        if (!("maxResponseLength" in $$source)) {
            this["maxResponseLength"] = 0;
        }
        if (!("appendMode" in $$source)) {
            this["appendMode"] = false;
        }
        if (!("soundOnComplete" in $$source)) {
            this["soundOnComplete"] = false;
        }
        if (!("captureImages" in $$source)) {
            this["captureImages"] = false;
        }
        if (!("flash" in $$source)) {
            this["flash"] = (new FlashSettings());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClipboardSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): ClipboardSettings {
        const $$createField6_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("flash" in $$parsedSource) {
            $$parsedSource["flash"] = $$createField6_0($$parsedSource["flash"]);
        }
        return new ClipboardSettings($$parsedSource as Partial<ClipboardSettings>);
    }
}

export class ConversationTurn {
    "role": string;
    "textContent": string;
    "images"?: string[];

    /** Creates a new ConversationTurn instance. */
    constructor($$source: Partial<ConversationTurn> = {}) {
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("textContent" in $$source)) {
            this["textContent"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConversationTurn instance from a string or object.
     */
    static createFrom($$source: any = {}): ConversationTurn {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("images" in $$parsedSource) {
            $$parsedSource["images"] = $$createField2_0($$parsedSource["images"]);
        }
        return new ConversationTurn($$parsedSource as Partial<ConversationTurn>);
    }
}

export class FlashAppearance {
    "color": string;
    "opacity": number;
    "fontSizePx": number;
    "textShadow": boolean;

    /** Creates a new FlashAppearance instance. */
    constructor($$source: Partial<FlashAppearance> = {}) {
        if (!("color" in $$source)) {
            this["color"] = "";
        }
        if (!("opacity" in $$source)) {
            this["opacity"] = 0;
        }
        if (!("fontSizePx" in $$source)) {
            this["fontSizePx"] = 0;
        }
        if (!("textShadow" in $$source)) {
            this["textShadow"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FlashAppearance instance from a string or object.
     */
    static createFrom($$source: any = {}): FlashAppearance {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FlashAppearance($$parsedSource as Partial<FlashAppearance>);
    }
}

export class FlashPayload {
    "text": string;
    "position": FlashPosition;
    "timing": FlashTiming;
    "appearance": FlashAppearance;
    "streamId": number;

    /** Creates a new FlashPayload instance. */
    constructor($$source: Partial<FlashPayload> = {}) {
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("position" in $$source)) {
            this["position"] = (new FlashPosition());
        }
        if (!("timing" in $$source)) {
            this["timing"] = (new FlashTiming());
        }
        if (!("appearance" in $$source)) {
            this["appearance"] = (new FlashAppearance());
        }
        if (!("streamId" in $$source)) {
            this["streamId"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FlashPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): FlashPayload {
        const $$createField1_0 = $$createType6;
        const $$createField2_0 = $$createType7;
        const $$createField3_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("position" in $$parsedSource) {
            $$parsedSource["position"] = $$createField1_0($$parsedSource["position"]);
        }
        if ("timing" in $$parsedSource) {
            $$parsedSource["timing"] = $$createField2_0($$parsedSource["timing"]);
        }
        if ("appearance" in $$parsedSource) {
            $$parsedSource["appearance"] = $$createField3_0($$parsedSource["appearance"]);
        }
        return new FlashPayload($$parsedSource as Partial<FlashPayload>);
    }
}

export class FlashPosition {
    "x": number;
    "y": number;
    "monitorLabel"?: string;

    /** Creates a new FlashPosition instance. */
    constructor($$source: Partial<FlashPosition> = {}) {
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FlashPosition instance from a string or object.
     */
    static createFrom($$source: any = {}): FlashPosition {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FlashPosition($$parsedSource as Partial<FlashPosition>);
    }
}

export class FlashSettings {
    "enabled": boolean;
    "previewLength": number;
    "position": FlashPosition;
    "timing": FlashTiming;
    "appearance": FlashAppearance;

    /** Creates a new FlashSettings instance. */
    constructor($$source: Partial<FlashSettings> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("previewLength" in $$source)) {
            this["previewLength"] = 0;
        }
        if (!("position" in $$source)) {
            this["position"] = (new FlashPosition());
        }
        if (!("timing" in $$source)) {
            this["timing"] = (new FlashTiming());
        }
        if (!("appearance" in $$source)) {
            this["appearance"] = (new FlashAppearance());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FlashSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): FlashSettings {
        const $$createField2_0 = $$createType6;
        const $$createField3_0 = $$createType7;
        const $$createField4_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("position" in $$parsedSource) {
            $$parsedSource["position"] = $$createField2_0($$parsedSource["position"]);
        }
        if ("timing" in $$parsedSource) {
            $$parsedSource["timing"] = $$createField3_0($$parsedSource["timing"]);
        }
        if ("appearance" in $$parsedSource) {
            $$parsedSource["appearance"] = $$createField4_0($$parsedSource["appearance"]);
        }
        return new FlashSettings($$parsedSource as Partial<FlashSettings>);
    }
}

export class FlashTiming {
    "mode": string;
    "fadeInMs": number;
    "fadeOutMs": number;
    "holdMs": number | null;

    /** Creates a new FlashTiming instance. */
    constructor($$source: Partial<FlashTiming> = {}) {
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("fadeInMs" in $$source)) {
            this["fadeInMs"] = 0;
        }
        if (!("fadeOutMs" in $$source)) {
            this["fadeOutMs"] = 0;
        }
        if (!("holdMs" in $$source)) {
            this["holdMs"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FlashTiming instance from a string or object.
     */
    static createFrom($$source: any = {}): FlashTiming {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FlashTiming($$parsedSource as Partial<FlashTiming>);
    }
}

export class NotificationSettings {
    "enabled": boolean;
    "showProcessingNotification": boolean;
    "showResponseNotification": boolean;
    "showErrorNotification": boolean;
    "showUpdateNotification": boolean;
    "showClipboardEmptyNotification": boolean;

    /** Creates a new NotificationSettings instance. */
    constructor($$source: Partial<NotificationSettings> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("showProcessingNotification" in $$source)) {
            this["showProcessingNotification"] = false;
        }
        if (!("showResponseNotification" in $$source)) {
            this["showResponseNotification"] = false;
        }
        if (!("showErrorNotification" in $$source)) {
            this["showErrorNotification"] = false;
        }
        if (!("showUpdateNotification" in $$source)) {
            this["showUpdateNotification"] = false;
        }
        if (!("showClipboardEmptyNotification" in $$source)) {
            this["showClipboardEmptyNotification"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NotificationSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): NotificationSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NotificationSettings($$parsedSource as Partial<NotificationSettings>);
    }
}

export class OAuthFlowResult {
    "code": string;
    "redirectUri": string;

    /** Creates a new OAuthFlowResult instance. */
    constructor($$source: Partial<OAuthFlowResult> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("redirectUri" in $$source)) {
            this["redirectUri"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OAuthFlowResult instance from a string or object.
     */
    static createFrom($$source: any = {}): OAuthFlowResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OAuthFlowResult($$parsedSource as Partial<OAuthFlowResult>);
    }
}

export class Settings {
    "autoLaunch": boolean;
    "mode": AIMode;
    "language": string;
    "systemPrompt": string;
    "temperature": number;
    "maxTokens": number;
    "shortcuts": ShortcutSettings;
    "tokenStats": TokenUsage;
    "clipboard": ClipboardSettings;
    "notifications": NotificationSettings;
    "onboardingCompleted": boolean;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("autoLaunch" in $$source)) {
            this["autoLaunch"] = false;
        }
        if (!("mode" in $$source)) {
            this["mode"] = AIMode.$zero;
        }
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("systemPrompt" in $$source)) {
            this["systemPrompt"] = "";
        }
        if (!("temperature" in $$source)) {
            this["temperature"] = 0;
        }
        if (!("maxTokens" in $$source)) {
            this["maxTokens"] = 0;
        }
        if (!("shortcuts" in $$source)) {
            this["shortcuts"] = (new ShortcutSettings());
        }
        if (!("tokenStats" in $$source)) {
            this["tokenStats"] = (new TokenUsage());
        }
        if (!("clipboard" in $$source)) {
            this["clipboard"] = (new ClipboardSettings());
        }
        if (!("notifications" in $$source)) {
            this["notifications"] = (new NotificationSettings());
        }
        if (!("onboardingCompleted" in $$source)) {
            this["onboardingCompleted"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField6_0 = $$createType9;
        const $$createField7_0 = $$createType10;
        const $$createField8_0 = $$createType11;
        const $$createField9_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("shortcuts" in $$parsedSource) {
            $$parsedSource["shortcuts"] = $$createField6_0($$parsedSource["shortcuts"]);
        }
        if ("tokenStats" in $$parsedSource) {
            $$parsedSource["tokenStats"] = $$createField7_0($$parsedSource["tokenStats"]);
        }
        if ("clipboard" in $$parsedSource) {
            $$parsedSource["clipboard"] = $$createField8_0($$parsedSource["clipboard"]);
        }
        if ("notifications" in $$parsedSource) {
            $$parsedSource["notifications"] = $$createField9_0($$parsedSource["notifications"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

export class ShortcutSettings {
    "processClipboardFlash": string;
    "adjustFlashPosition": string;
    "emergencyQuit": string;

    /** Creates a new ShortcutSettings instance. */
    constructor($$source: Partial<ShortcutSettings> = {}) {
        if (!("processClipboardFlash" in $$source)) {
            this["processClipboardFlash"] = "";
        }
        if (!("adjustFlashPosition" in $$source)) {
            this["adjustFlashPosition"] = "";
        }
        if (!("emergencyQuit" in $$source)) {
            this["emergencyQuit"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShortcutSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): ShortcutSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ShortcutSettings($$parsedSource as Partial<ShortcutSettings>);
    }
}

export class StreamChunk {
    "streamId": number;
    "text": string;
    "isFinished": boolean;
    "inputTokens": number | null;
    "outputTokens": number | null;
    "contentType": string;

    /** Creates a new StreamChunk instance. */
    constructor($$source: Partial<StreamChunk> = {}) {
        if (!("streamId" in $$source)) {
            this["streamId"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("isFinished" in $$source)) {
            this["isFinished"] = false;
        }
        if (!("inputTokens" in $$source)) {
            this["inputTokens"] = null;
        }
        if (!("outputTokens" in $$source)) {
            this["outputTokens"] = null;
        }
        if (!("contentType" in $$source)) {
            this["contentType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamChunk instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamChunk {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StreamChunk($$parsedSource as Partial<StreamChunk>);
    }
}

export class TokenUsage {
    "inputTokens": number;
    "outputTokens": number;
    "totalTokens": number;

    /** Creates a new TokenUsage instance. */
    constructor($$source: Partial<TokenUsage> = {}) {
        if (!("inputTokens" in $$source)) {
            this["inputTokens"] = 0;
        }
        if (!("outputTokens" in $$source)) {
            this["outputTokens"] = 0;
        }
        if (!("totalTokens" in $$source)) {
            this["totalTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TokenUsage instance from a string or object.
     */
    static createFrom($$source: any = {}): TokenUsage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TokenUsage($$parsedSource as Partial<TokenUsage>);
    }
}

export class UpdateStatus {
    "available": boolean;
    "version"?: string;
    "currentVersion"?: string;
    "message": string;
    "releaseUrl"?: string;
    "downloadUrl"?: string;
    "assetName"?: string;

    /** Creates a new UpdateStatus instance. */
    constructor($$source: Partial<UpdateStatus> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateStatus($$parsedSource as Partial<UpdateStatus>);
    }
}

// Private type creation functions
const $$createType0 = ConversationTurn.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = ClipboardImage.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = FlashSettings.createFrom;
const $$createType6 = FlashPosition.createFrom;
const $$createType7 = FlashTiming.createFrom;
const $$createType8 = FlashAppearance.createFrom;
const $$createType9 = ShortcutSettings.createFrom;
const $$createType10 = TokenUsage.createFrom;
const $$createType11 = ClipboardSettings.createFrom;
const $$createType12 = NotificationSettings.createFrom;
