//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../../../../JGSimi/Hat-Cross/apps/hat-flash/internal/models/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "auth:required": $$createType0,
        "flash:show": $$createType1,
        "settings:changed": $$createType2,
        "shortcut:pressed": $$createType0,
        "stream:chunk": $$createType3,
        "stream:done": $$createType0,
    }));
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = models$0.FlashPayload.createFrom;
const $$createType2 = models$0.Settings.createFrom;
const $$createType3 = models$0.StreamChunk.createFrom;

configure();
