// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as models$0 from "../../../../JGSimi/Hat-Cross/apps/hat-flash/internal/models/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "auth:required": { [_ in string]?: any };
            "clipboard:failed": string;
            "clipboard:started": any;
            "flash:hide": any;
            "flash:show": models$0.FlashPayload;
            "settings:changed": models$0.Settings;
            "shortcut:pressed": { [_ in string]?: any };
            "stream:chunk": models$0.StreamChunk;
            "stream:done": { [_ in string]?: any };
        }
    }
}
