// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function IsAutostartEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(507421429);
}

export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(3443844632);
}

export function SetAutostart(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3209856454, enabled);
}
