// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function Process(): $CancellablePromise<models$0.ClipboardPayload> {
    return $Call.ByID(4252108673).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ReadImage(): $CancellablePromise<models$0.ClipboardImage | null> {
    return $Call.ByID(1253229053).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ReadText(): $CancellablePromise<string> {
    return $Call.ByID(3245136535);
}

export function WriteText(text: string): $CancellablePromise<void> {
    return $Call.ByID(2930373676, text);
}

// Private type creation functions
const $$createType0 = models$0.ClipboardPayload.createFrom;
const $$createType1 = models$0.ClipboardImage.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
