// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function Current(): $CancellablePromise<models$0.FlashPayload | null> {
    return $Call.ByID(3680473517).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Hide(): $CancellablePromise<void> {
    return $Call.ByID(2989440392);
}

export function Show(payload: models$0.FlashPayload): $CancellablePromise<void> {
    return $Call.ByID(3654763649, payload);
}

// Private type creation functions
const $$createType0 = models$0.FlashPayload.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
