// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function Get(): $CancellablePromise<models$0.Settings> {
    return $Call.ByID(3174315131).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Save(settings: models$0.Settings): $CancellablePromise<void> {
    return $Call.ByID(2216955660, settings);
}

// Private type creation functions
const $$createType0 = models$0.Settings.createFrom;
